#!/usr/bin/env bash
erb /app/nginx/nginx.conf.erb > /app/nginx/nginx.conf

mkdir -p /app/nginx/logs
touch /app/nginx/logs/access.log /app/nginx/logs/error.log
(tail -f -n 0 /app/nginx/logs/*.log &)

# launch all mono processes
/app/mono/bin/mono /app/*.exe

# launch nginx
/app/nginx/nginx -p /app/nginx -c /app/nginx/nginx.conf