#!/usr/bin/env bash
erb /app/nginx/nginx.conf.erb > /app/nginx/nginx.conf

mkdir -p /app/nginx/logs
touch /app/nginx/logs/access.log /app/nginx/logs/error.log
(tail -f -n 0 /app/nginx/logs/*.log &)

/app/mono/bin/mono /app/*.exe